### ISSUE TITLE
Game window always go back to main screen

### ISSUE THREAD

**Issue by qwertyue** [Jarcho/d2dx#27]
I have two screens: main screen and secondary screen.
Every time I open the game, the game window appears on the main screen and I drag it to the secondary screen and play. 
When I click on option 'save and exit game', the game window goes back to the main screen

**Comment by Jarcho** [comment]
Do you have the window position set in `d2dx.cfg`? The game window will move there every time the game changes resolution (it really shouldn't if the window has been moved manually).

**Comment by Jarcho** [comment]
Should be fixed in the latest release.

**Comment by qwertyue** [comment]
I just tested it without setting the position in d2dx.cfg, but this problem still occurs.

**Comment by qwertyue** [comment]
After testing, the current situation is as follows:
Only on one monitor: after dragging the game window, re-entering the game will not happen the window position restoration.

Two monitors: after dragging the game window to the secondary screen and re-entering the game, the window will appear on the main screen.

**Comment by qwertyue** [comment]
Found a new issue: Placing the game window on the secondary monitor causes the mouse scroll wheel to be unable to scroll properly.

**Comment by Jarcho** [comment]
Latest version has a rewrite of the window positioning code. Should now take multiple monitors correctly.

**Comment by qwertyue** [comment]
tested, the window reset issue has been resolved. 

However, after scrolling with the mouse wheel on the secondary screen, the pointer returns to the primary screen.

**Comment by Jarcho** [comment]
The scroll wheel issue is fixed in 0.103.4.
