### ISSUE TITLE
hi~Mr. Jarcho，I find some not smooth issues.

### ISSUE THREAD

**Issue by weili0677** [Jarcho/d2dx#5]
I test many your commits version,and after the [Smoothen out frame jitter for motion prediction] version,I find the game become to not smooth. I don't know why.Can you check it?

The smoothly commit is（all before this commits is all smoothly）:
[Smoothen out frame jitter for motion prediction](https://github.com/Jarcho/d2dx/commit/3644d8b81c80db2ebb8098a8ddc566405adeff42)

The not smoothly commit is（all after this commits is all not smoothly）:
[Fix unit motion predictor](https://github.com/Jarcho/d2dx/commit/0fe5ebad9212060a3e052889477376ca1df8f0d6)

**Comment by Jarcho** [comment]
This should be fixed as of the [2022-12-24 release](https://github.com/Jarcho/d2dx/releases/tag/2022-12-24).

**Comment by weili0677** [comment]
> 

Thang you so much。I will test it right now.

**Comment by weili0677** [comment]
> This should be fixed as of the [2022-12-24 release](https://github.com/Jarcho/d2dx/releases/tag/2022-12-24).

Hi，Mr. Jarcho，I think 12-24 release has not fix the bug.You can use the Barb's skill "Leap" for test, It will more obvious.

**Comment by Jarcho** [comment]
Can you run [this version)[https://github.com/Jarcho/d2dx/releases/download/2022-12-24/d2dx-2022-12-24-profile.zip] and upload the `d2dx_log.txt` file?

**Comment by weili0677** [comment]
> Can you run [this version)[https://github.com/Jarcho/d2dx/releases/download/2022-12-24/d2dx-2022-12-24-profile.zip] and upload the `d2dx_log.txt` file?

https://drive.google.com/file/d/1EpCZNf3QiLuP2Xwx_w0AiAQpwZpnO8vV/view?usp=sharing

**Comment by skylight102** [comment]
Hi Jarcho, it seems like your latest version makes improvements  **_without_** the "FreeRes" but when I'm playing PD2 with freeres, it causes a lot of FPS lag, to the point where eventually it will freeze for seconds at a time. I haven't experienced this issue with your version: "may fix fps drop after playing for some time"

**Comment by Jarcho** [comment]
Latest version is (this one)[https://github.com/bolrog/d2dx/files/10318329/d2dx-test.zip] which I never really made a release for.

**Comment by skylight102** [comment]
> Latest version is [this one](https://github.com/bolrog/d2dx/files/10318329/d2dx-test.zip) which I never really made a release for. Can you check and see how that one works?

Hi Jarcho, I tested this and whilst it seems to be a significant improvement, I'm pretty confident that it is not as smooth as your older version "may fix fps drop after playing for some time"

I have asked Weili to test, he is better at this than me.

**Comment by weili0677** [comment]
> Latest version is [this one](https://github.com/bolrog/d2dx/files/10318329/d2dx-test.zip) which I never really made a release for. Can you check and see how that one works?

also not smooth,even 800x600 or any resulotions

**Comment by Jarcho** [comment]
Latest release is back to using the old prediction code.
